[package]
name = "file_system"
version = "0.1.0"
edition = "2024"

[dependencies]
fuser = "0.16.0"
libc = "0.2.177"
rustc-serialize = "0.3.25"
time = "0.3.44"
serde = { version = "1", features = ["derive"] }
serde_json = "1"